version: '3.3'

services:

  client:
    build: ./client
    restart: always
    image: task-client-image
    container_name: task-client-container
    ports:
      - "4000:4000"   
    depends_on:
      - server            
    networks:
      - backend
      
  server:
    build: ./server
    restart: always
    image: task-server-image
    container_name: task-server-container
    ports:
      - "9090:9090"        
    depends_on:
      - db
    networks: 
      - backend
      - frontend         

  db:     
    image: postgres:10-alpine
    restart: always
    #ports:
    # - "5445:5432"
    container_name: task-postgres-container
    environment:
      TASK_MANAGER_USER: task_admin
      TASK_MANAGER_PASSWORD: 123qwe
      TASK_MANAGER_DATABASE: task_db    
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend    
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data


networks:
  backend:
  frontend:        
