version: '3.3'

services:

  postgres:
    build: ./postgres      
    restart: always
    expose:
      - 5432      
    ports:
      - 5432:5432
    image: postgres-image
    container_name: postgres-container
    environment:
      - TASK_MANAGER_USER=task_manager_admin
      - TASK_MANAGER_PASSWORD=123qwe
      - TASK_MANAGER_DATABASE=task_manager_db
    volumes:
    - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql          

  task-manager:
    build: ./server
    image: task-manager-image
    container_name: task-manager-container
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - postgres    

networks:
  infranet:   
