version: '3.3'

services:

  client:
    build: ./client
    restart: always
    image: task-client-image
    container_name: task-client-container
    ports:
      - "4000:4000"   
    depends_on:
      - server            
    networks:
      - back-front
      
  server:
    build: ./server
    restart: always
    image: task-server-image
    container_name: task-server-container
    ports:
      - "9090:9090"        
    depends_on:
      - db
    networks: 
      - back-front
      - db-back         

  db:     
    image: postgres:10-alpine
    restart: always
    ports:
     - "5432:5432"
    container_name: task-postgres-container
    environment:
      POSTGRES_USER: task_admin
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: task_db    
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - db-back    
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data


networks:
  back-front:
  db-back:        
