server:
  port: 7070
  servlet:
      session:
        timeout: 600s

spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
      table-name: SPRING_SESSION

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
#      javax:
#        persistence:
#          charedCache:
#            mode: ENABLE_SELECTIVE
      hibernate:
#        cache:
#          use_second_level_cache: true
#          region:
#            factory_class: org.hibernate.cache.ehcache.internal.EhcacheRegionFactory

        dialect: org.hibernate.dialect.PostgreSQL93Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        current_session_context_class: thread
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123qwe
    driverClassName: org.postgresql.Driver
    initialization-mode: always

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org:
      springframework:
#        security: DEBUG
        web: DEBUG

      hibernate: ERROR

#    net:
#      sf:
#        ehcache:
#          DEBUG