server:
  port: 7575
  servlet:
      session:
        timeout: 600s

spring:
#  mvc:
#    throw-exception-if-no-handler-found: true
#
#  resources:
#    add-mappings: false

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
      table-name: SPRING_SESSION

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        dialect: org.hibernate.dialect.PostgreSQL93Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        current_session_context_class: thread
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/tracker_db
    username: tracker_admin
    password: 123qwe
    driverClassName: org.postgresql.Driver
    initialization-mode: always

#  postgres-container

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org:
      springframework:
#        security: DEBUG
        web: DEBUG

      hibernate: ERROR

#    net:
#      sf:
#        ehcache:
#          DEBUG

#log4j:
#  logger:
#    org:
#      hibernate:
#        SQL: TRACE
#        type: TRACE

