server:
  port: 8080

---

logging.level.root: INFO

spring:
  profiles.active: development

  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL93Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        current_session_context_class: thread
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    initialization-mode: always
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: test
    password: test

#    platform: postges
#    username: stylist_admin
#    password: 123qwe
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/stylist_db

---

logging.level.org: ERROR

spring:
  profiles: prodaction

  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL93Dialect
        current_session_context_class: thread
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    initialization-mode: always
    platform: postges
    username: stylist_admin
    password: 123qwe
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres-container:5432/stylist_db